name: Bug Report
description: Report a problem with an existing skill
labels: ["bug"]
body:
  - type: input
    id: skill
    attributes:
      label: Skill name
      placeholder: e.g. commit
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Claude Code version
      placeholder: e.g. 1.2.3
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you do, and what went wrong?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
